### ISSUE TITLE
Add cancel token option to startDownload

### ISSUE THREAD

**Issue by hossam-96** [edjostenes/download_assets#11]
Expose the cancel token option in the Dio API request to the user to be able to cancel the request

![Screenshot 2023-03-06 at 12 33 52 AM](https://user-images.githubusercontent.com/26495484/222989725-d34cc53f-706b-4845-a58a-a666d6aaa9f0.png)

**Comment by edjostenes** [comment]
Hi, the package was updated to version 3.0.5. The cancel feature was added, could you test it, please?

Sorry for the delay in order to add new features. :D
