### ISSUE TITLE
Constructor is calling function which is async

### ISSUE THREAD

**Issue by gamelaster** [edjostenes/download_assets#6]
The `_init` function is async, and called from `DownloadAssetsControllerImpl` constructor.
The problem with this is, that you can't use Asset Controller in `initState` function or any other function, which is called before the `_init` finishes execution.

**Comment by edjostenes** [comment]
Hi, thank you for your reply.
I'm changing the constructor and adding two new params to the startDownload method, which are:

* directoryPath; The directory where the file will be downloaded (default value: assets)
* zippedFile: The name of the file (default value: assets.zip);

After this change, the constructor will be free of any code.
Do you have any other suggestions on how to improve this piece of code?
You can follow these changes on the dev branch.

**Comment by gamelaster** [comment]
Hi @edjostenes ,

I checked your changes, and they are good! 😊 

Also, your library works on Windows good so far without any modifications, so you can mark it as supported, although, `getApplicationPath` returns Documents folder of current user, which isn't much perfect location for assets, so it would be good to have this configurable 😊 

Thank you for your time

**Comment by gamelaster** [comment]
One note, I found bug, that you can't call `assetsDirAlreadyExists` until you don't call `startDownload`.

**Comment by edjostenes** [comment]
> Hi @edjostenes ,
> 
> I checked your changes, and they are good! 😊
> 
> Also, your library works on Windows good so far without any modifications, so you can mark it as supported, although, `getApplicationPath` returns Documents folder of current user, which isn't much perfect location for assets, so it would be good to have this configurable 😊
> 
> Thank you for your time

**Comment by edjostenes** [comment]
> One note, I found bug, that you can't call `assetsDirAlreadyExists` until you don't call `startDownload`.

Hi, @gamelaster, I tried to reproduce this bug without success. I was able to call 'assetsDirAlreadyExists' in the initState without any problem. The app is throwing any error messages?

Thank you for the hint related to the windows, I had never tested on it.

**Comment by edjostenes** [comment]
I just updated the dev branch with some improvements. If you could validate it I will appreciate it a lot. :)

**Comment by gamelaster** [comment]
Hi @edjostenes and thank you for your work.
About `assetsDirAlreadyExists`, the problem is that, that until you don't call `startDownload`, the `assetsDirAlreadyExists` will return `false` every time. Also,the `assetsDir` is null too until download starts, thus, you can't check if the assets are existing before the download. Probably, the directoryPath should be really in constructor, but before using all the functions, async `init` call should be called.

About API changes, I would recommend to keep onComplete and onProgress optional, or maybe fully remove `onComplete`, since the function is await, and `onComplete` is when the future is completed. 

Once again, thank you for your time 😊

**Comment by edjostenes** [comment]
Thank you for your reply.

I've made the changes that you suggested. Now you have to use the init async method to set up the assetsDir path, you can call this method in the initState or in the app initialization. I've updated the example as well.
Could you validate if everything is working as expected?

**Comment by gamelaster** [comment]
@edjostenes : sorry, due to holidays I wasn't able to test your changes, although, I will definitely test it in following days and will let you know about the results. Thank you 😊

**Comment by gamelaster** [comment]
Hi @edjostenes , I tested your version, and it works good! 😊 Thank you very much
