### ISSUE TITLE
App crash during big file downloading

### ISSUE THREAD

**Issue by tmp78** [edjostenes/download_assets#7]
I'm not sure what causes this problem. I have learning app with video assets -about 750 MB. The zip file downloads to about 86 percent and then the application crashes. After reducing the file size to about 400 MB everything works great.
This happens on the emulator with 6 GB free disk space and 1.5 GB RAM.
Download process on physical device with 8GB RAM and 256GB disk space has completed. Why? Does device needs more RAM, disk space for downloading/unpacking? Does this mean that on older/weaker devices it is impossible to download a large file?

**Comment by tmp78** [comment]
It seems it's all about not enough RAM. I increased it to 2 GB - still not enough. But 3 GB solved the problem.

**Comment by edjostenes** [comment]
Hi, thank you for your reply, I`m very glad that my lib could be useful in your solution. But, you've already "solved" this issue, right?

**Comment by tmp78** [comment]
Yep. Sorry, I'm closing it right now.
