### ISSUE TITLE
Working example for MacOS

### ISSUE THREAD

**Issue by johnareid54** [edjostenes/download_assets#9]
Could you produce an example that works for MacOS, it works fine in IOS but fails when I run it in MacOS it comes up with:

Exception has occurred.
FileSystemException (FileSystemException: Cannot open file, path = '/Users/john/Library/Containers/com.example.down2/Data/Documents/assets/dart.jpeg' (OS Error: No such file or directory, errno = 2))

**Comment by Farial-mahmod** [comment]
@johnareid54  , have you ensured the permission in AndroidManifest.xml file?

**Comment by johnareid54** [comment]
Thanks - I understand it's a permission issue. I changed the manifest and <key>com.apple.security.network.client</key>
<true/> to macos/Runner/DebugProfile.entitlements and macos/Runner/Release.entitlements.  However the error still exists. I will work with a basic http example and get the it working first and then apply it to your download_assets.

**Comment by johnareid54** [comment]
Regret I cannot get it to work on my m1 macBookAir, has anyone got it working in MacOS?

**Comment by johnareid54** [comment]
OK I have now got it to working, wish I could say why it is working now, just did a new project and added the permissions as before. I have done nothing different but it is now working!
